apiVersion: v2
name: strike
description: Strike Gaming Cloud Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.15.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 22.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled

